name: 🐛 Bug Report
description: Submit issues to improve the mod stability. Make sure the mod is up to date before reporting bugs.
title: "[Bug] Title"
assignees: wen-wen520
labels:
  - "🐛 Bug"
body:
- type: textarea
  id: description
  validations:
    required: true
  attributes:
     label: Description
     description: Please provide a brief description of the issue you encountered

- type: textarea
  id: screenshots
  attributes:
     label: Screenshots
     description: If possible, submit screenshots to better illustrate the issue

- type: textarea
  id: recurrent
  validations:
    required: true
  attributes:
     label: Steps to Reproduce
     description: Steps to reproduce the issue

- type: checkboxes
  id: target-game-version
  attributes:
    label: Game Version
    description: Select the Minecraft client version where the issue was found (the right side is the format of mod)
    options:
      - label: "1.21"
      - label: "1.21.1"
      - label: "1.21.2"
      - label: "1.21.3"
      - label: "1.21.4"
      - label: "1.21.5"
      - label: "1.21.6"
      - label: "1.21.7"
      - label: "1.21.8"
      - label: "1.21.9"
      - label: "1.21.10"
  validations:
    required: true